language: c # :(

env:
        global:
                - DISTRO=debian-9
                - PACKAGE=ocaml-test-base
                - INSTALL=false
                - OPAMYES=true
                - PINS="base" #needed for any OCAML_VERSION > 4.06, so use it unilaterally
        matrix:
                - OCAML_VERSION=4.06.1+afl
                - OCAML_VERSION=4.07.0+rc2+afl
                - OCAML_VERSION=4.07.0+trunk+afl

before_install:
- sudo sysctl kernel.core_pattern=core

install: wget https://raw.githubusercontent.com/yomimono/ocaml-ci-scripts/opam2-base/.travis-docker.sh

script: bash -ex .travis-docker.sh
