language: c

env:
        global:
                - DISTRO=debian-9
                - PACKAGE=ocaml-test-stdlib
                - INSTALL=false
                - OPAMYES=true
        matrix:
                - OCAML_VERSION=4.06.1+afl

before_install:
- sudo sysctl kernel.core_pattern=core

install: wget https://raw.githubusercontent.com/yomimono/ocaml-ci-scripts/opam2-base/.travis-docker.sh

script: bash -ex .travis-docker.sh
