sudo: required

language: c

services:
- docker

before_install:
- sudo sysctl kernel.core_pattern=core
- sudo apt-get update
- sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
- docker build -t alltests:latest .

script:
- docker run alltests:latest
