language: c # :(

env:
        global:
                - DISTRO=debian-9
                - PACKAGE=ocaml-test-base
                - INSTALL=false
                - OPAMYES=true
                - PINS="base bun:https://github.com/yomimono/ocaml-bun.git#always-output"
                  #pinned base is needed for any OCAML_VERSION > 4.06, so use it unilaterally
                  #bun pin is a fix for a race condition where we might not output if both fuzzers
                  #terminate close to simultaneously; version 0.3.3 should contain a fix
        matrix:
                - OCAML_VERSION=4.06.1+afl
                - OCAML_VERSION=4.07.0+rc2+afl
                - OCAML_VERSION=4.07.0+trunk+afl

before_install:
- sudo sysctl kernel.core_pattern=core

install: wget https://raw.githubusercontent.com/yomimono/ocaml-ci-scripts/opam2-base/.travis-docker.sh

script: bash -ex .travis-docker.sh
