language: c

env:
        global:
                - HUB_USER=yomimono
                - DISTRO=debian-9
                - PACKAGE=ocaml-test-stdlib
                - INSTALL=false
                - PINS="bun:https://github.com/yomimono/ocaml-bun.git"
        matrix:
                # docker hub (the ultimate source of the base images) doesn't allow + in names, hence the _
                - OCAML_VERSION=4.04.0_afl
                - OCAML_VERSION=4.05.0_afl
                - OCAML_VERSION=4.06.0_afl

before_install:
- sudo sysctl kernel.core_pattern=core

install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh

script: bash -ex .travis-docker.sh
